[config]
reload_apps = false
set_wallpaper = false
prefix = '@'

[config.reload_apps_list]
waybar = false
kitty = false
gtk_theme = false
dunst = false

[templates]
gtk = { input_path = '~/.config/matugen/templates/gtk-colors.css', output_path = '~/.cache/matugen/gtk.css' }
qt5ct = { input_path = '~/.config/matugen/templates/qt5ct-colors.conf', output_path = '~/.config/qt5ct/colors/material.conf' }
qt6ct = { input_path = '~/.config/matugen/templates/qt6ct-colors.conf', output_path = '~/.config/qt6ct/colors/material.conf' }
hypr = { input_path = '~/.config/matugen/templates/hyprland-colors.conf', output_path = '~/.config/hypr/configs/colors.conf' }
eww = { input_path = '~/.config/matugen/templates/eww-colors.scss', output_path = '~/.config/eww/style/colors.scss' }
dunst = { input_path = '~/.config/matugen/templates/dunstrc-colors', output_path = '~/.config/dunst/dunstrc' }
waybar = { input_path = '~/.config/matugen/templates/waybar-colors.css', output_path = '~/.config/waybar/colors.css' }
rofi = { input_path = '~/.config/matugen/templates/rofi-colors.rasi' , output_path = '~/.config/rofi/colors.rasi' }
alacritty = { input_path = '~/.config/matugen/templates/alacritty-colors.toml', output_path = '~/.config/alacritty/themes/colors.toml' }
kitty = { input_path = '~/.config/matugen/templates/kitty-colors.conf', output_path = '~/.config/kitty/themes/colors.conf' }
cava = { input_path = '~/.config/matugen/templates/cava-colors', output_path = '~/.config/cava/config' }
btop = { input_path = '~/.config/matugen/templates/btop-colors.theme', output_path = '~/.config/btop/themes/material.theme' }
