import = [
    "~/.config/alacritty/themes/colors.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 100, lines = 80 }
padding = { x = 10, y = 8 }
opacity = 0.8
blur = true

[scrolling]
multiplier = 3

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 500
unfocused_hollow = true

[font]
size = 11.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
  { key = "K", mods = "Control", action = "ClearHistory" },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "Q", mods = "Command", action = "Quit" },
  { key = "N", mods = "Command", action = "SpawnNewInstance" },
  { key = "Return", mods = "Command", action = "ToggleFullscreen" }
]

[shell]
program = "/bin/zsh"

